name: Triple Trijam
# when the build event will happen
on:
    # triggers the build only on push to main branch or release
    push:
        branches:
            - master

    release:
        types: [published, created, edited]

# a list of jobs to be done
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - .
        unityVersion:
          - 2019.4.1f1
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - WebGL # WebGL.

    steps:
    # checkout the latest commit
    - name: Checkout Latest commit on master branch
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        lfs: true

    # cache all library files
    - name: Cache Unity Library files
      uses: actions/cache@v2
      with:
        path: ${{ matrix.projectPath }}/Library
        key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
        restore-keys: |
          Library-${{ matrix.projectPath }}-
          Library-

    # Test
    - name: Run tests
      uses: game-ci/unity-test-runner@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}


    # Build
    - name: Build project
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        unityVersion: ${{ matrix.unityVersion }}
        targetPlatform: ${{ matrix.targetPlatform }}
        allowDirtyBuild: true

    # Output
    - uses: actions/upload-artifact@v2
      with:
          name: Build
          path: build
